# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=250)),
                ('classification', models.CharField(max_length=10)),
            ],
        ),
    ]
